trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- script: |
- task: AzureCLI@2
  inputs:
    azureSubscription: 'identity-azuredevops'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az group create -n rg-demo -l westeurope'''